### ISSUE TITLE
upstream could pick up a client in quit state

### ISSUE THREAD

**Issue by mzhang6666** [samaritan-proxy/samaritan#32]
keep sam running over night with goland, in some case, redis cli receive unexpected error like "backend exit". possibly this behavior cause by client was in quit state but never got chance be removed from upstream cache. 

involve double check for guarantee the availability of client instance, remove createClientCalls cache

c, ok := u.loadClients()[addr]

	if c != nil {
		if ok {
			select {
			case <-c.quit:
				logger.Fatal("unexpected behavior, client is in quit status.")

				// clear client cache
				c.quitOnce.Do(func() {
					close(c.quit)
				})
				u.removeClient(addr)
			default:
				return c, nil
			}
		}
	}

**Comment by kirk91** [comment]
@mzhang6666 Thanks for your feedback first, but this is a normal case and result is as expected.

When redis server is not accessible due to network broken or  unexpected crash, the client will quit. During the period of quitting, the requests that should  be routed to it will fail, and the error message is `backend exit`.  Unfortunately,  this case cannot be eliminated if we add more checks.

If want to find the root cause, you can check the Sam's log and the status of redis server.

**Comment by mzhang6666** [comment]
short term outage is acceptable during a quitting process, could recovered by client side fault tolerance. but in some particular case, even if client was quit for a while, "c, _ := u.loadClients()[addr]" still return a client instance in quit state, "backend exit" respond to client indefinitely that's the case we are talking about.

**Comment by kirk91** [comment]
@mzhang6666 Sorry, I may have missed some key information like `"backend exit" respond to client indefinitely`

In normal, the client will be removed immediately from upstream once it's done, here is the code: [upstream.go#L266](https://github.com/samaritan-proxy/samaritan/blob/master/proc/redis/upstream.go#L266) . But if the response is always "backend exit", there is something wrong which causes that the client hangs.

I try to reproduce it by simulating network broken locally,  but failed. Could you provide more context such as how to reproduce this issue?

**Comment by mzhang6666** [comment]
@kirk91 thx for test this scenario, could reproduced in macos+goland with a nightly test, may cause by the instability of IDE environment.  issue can be closed if never occurred in a live env

**Comment by mzhang6666** [comment]
@kirk91 that's exactly the same repo steps while keep sending pipeline hgetall thru sam. Evicting a quit client from cache is necessarily not only in loopWrite() but in earlier phase before MakeRequestToHost()

**Comment by kirk91** [comment]
@mzhang6666 Yep, you are right. I would appreciate if you can make a pull request.

**Comment by kirk91** [comment]
@mzhang6666 The fix has been merged into master branch. Do you have time to test again with the latest codes?

**Comment by mzhang6666** [comment]
> @mzhang6666 The fix has been merged into master branch. Do you have time to test again with the latest codes?

no more occurrence after I engaged a protective code regarding quit client instance
